name: Notify Atlas Update

on:
  push:
    branches:
      - main
    paths:
      - 'microdatos/**'

jobs:
  notify-atlas:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository dispatch event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.YOUR_PAT_SECRET_NAME }}" \
            https://api.github.com/repos/matuteiglesias/encuestador-de-hogares/dispatches \
            -d '{"event_type":"models-updated"}'
